blog:
    path: /blog/{page}
    defaults:   { _controller: AcmeBlogBundle:Blog:index, page: 1 }
    requirements:
        page: \d+

blog_show:
    path:       /blog/{slug}
    defaults:   { _controller: AcmeBlogBundle:Blog:show }
